language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
jobs:
  include:
    - stage: lint
      script: "npm run lint"
    - stage: test
      script: "npm run test"
